### ISSUE TITLE
Bluetooth Serial commands

### ISSUE THREAD

**Issue by lupus78** [pjalocha/esp32-ogn-tracker#18]
Pawel, am I right that you can not send configuration commands via the Bluetooth Serial interface?

I tried but no effect. See the attached screenshot, $POGNS,Verbose=0 should turn off the messages.

![Screenshot_20200617-120251_Serial Bluetooth Terminal](https://user-images.githubusercontent.com/5301520/84885149-eca26180-b092-11ea-9b86-0808ca87e176.jpg)

**Comment by Paulie92** [comment]
Hi,

 I heve exactly the same problem. I was also trying to send the command via Arduino IDE serial monitor also without success. But I am wondering, what should mean what is mentioned at pawel's instructions: _"To list all parameters with their values send Ctrl-C (**software and hardware handshake must be OFF**)."_ The problem could be here, but I don't know what the "handshake" is and how to disable it. Does anyone have an idea or hint?

**Comment by lupus78** [comment]
That is not the same issue. Via the USB cable the terminal works. The Aurdino IDE is not suitable to send the Ctrl-C command, you should use the make's built in serial monitor or minicom to send the Ctrl-C and other key combinations. Read this for more details: http://wiki.glidernet.org/esp32-ogn-tracker

**Comment by pjalocha** [comment]
I confirm there is no data path from the BT incoming data to the console input, thus I shall create it, possibly today.

**Comment by Paulie92** [comment]
The new version does not work for me now at all. I even cannot cannot connect via bluetooth. Also via the the USB serial connection I cannot see the NMEA data flow. It looks lile the ESP is only rebooting again and again.

**Comment by pjalocha** [comment]
Yes, sorry, a bug, fixed now, please try again.

**Comment by Paulie92** [comment]
The ESP is running now but the bluetooth commands still not for me.

**Comment by lupus78** [comment]
Pawel, thanks the Bluetooth it working! This opens up the possibility to make a desktop or mobile app for configuration. 

I suggest to move someof the functional settings from config.h to parameters. Like setting which NMEA sentence to send, or config for Vario parameters. What do you think?
